name: API Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Chrome
      uses: browser-action/setup-chrome@latest

    - name: Setup Gradle
      run: chmod +x gradlew

    - name: Execute Test
      run: ./gradlew clean apitest

    - name: Archive Test Result
      uses: action/upload-artifact@v4
      if: always()
      with:
        name: Cucumber Report
        path: reports
      
      
